#!/bin/sh
# by Mary McGrath
set -x

branch=$1
shift

src="$HOME/Work"
prototype_dir="$src/prototype"
dir="$src/$branch"
depot="$src/.raicode-depots/$branch"

if [[ "X$1" == "X-d" ]] ; then
	rm -rf $dir
	rm -rf $depot
	set +x
	exit
fi

#mkdir -p $dir
mkdir -p $depot

cd $prototype_dir
git pull --rebase
#git clone git@github.com:RelationalAI/raicode.git $branch
cd $src
cp -r $prototype_dir $branch
cd $branch
#git fetch origin
git checkout --track origin/$branch || git checkout -b $branch
#pre-commit install

# Set up a separate depot for this branch.
mkdir -p $depot/config $depot/logs
ln -s $HOME/.julia/config/startup.jl $depot/config/startup.jl
ln -s $HOME/.julia/logs/repl_history.jl $depot/logs/repl_history.jl

# Use shadowenv https://shopify.github.io/shadowenv/getting-started/)
# to manage environment variables per-directory.
# Make sure .shadowenv.d is in your global gitignore.
env=.shadowenv.d
mkdir -p $env
echo "(env/set \"RAI_PATH\" \"$dir\")" > $env/env.lisp
echo "(env/set \"JULIA_PROJECT\" \"$dir\")" >> $env/env.lisp
echo "(env/set \"JULIA_DEPOT_PATH\" \"$depot:\")" >> $env/env.lisp
echo "(env/set \"JULIA_LOAD_PATH\" \"$depot:$HOME/.julia:\")" >> $env/env.lisp
echo "(env/set \"RAI_PRINT_CONSTANTS_HASHED\" \"42\")" >> $env/env.lisp
#echo "(env/set \"RAI_TRACEVIEW\" \"true\")" >> $env/env.lisp

shadowenv trust

set +x
